config/routes.rb
Spree::Core::Engine.routes.prepend do
  
  namespace :admin do
#		callback for jQuery sort action
   match 'taxons/reorder_products/:id' => 'taxons#reorder_products', :via => :put
   match 'product_taxons/positions' => 'product_taxons#positions', :as => :product_sort
   match 'product_taxons/taxon_sort' => 'product_taxons#taxon_sort', :as => :taxon_sort
    resources :product_taxons do
      collection do
        get :positions
      end
    end
  end  
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  has_many :product_taxons
  has_many :taxons, :through=>:product_taxons

  #default_scope :include=>:product_taxons, :order=>"product_taxons.position"
  scope :ordered, {:include=>:product_taxons, :order=>"spree_product_taxons.position"}

  scope :available, lambda { |*args| 
    where(["spree_products.available_on <= ?", args.first || Time.zone.now]).
      includes(:product_taxons).
      order('spree_product_taxons.taxon_id, spree_product_taxons.position') #group positions by taxon so that home page (0) works
  }

  after_create :create_product_taxon

  def create_product_taxon
    # new product added, create initial product_taxon assignment so that products on the main page can also be sorted.
    Spree::ProductTaxon.create(:product_id=>self.id, :taxon_id=>0)
  end

  def in_taxon?(taxon)
    case taxon
      when String
        self.taxons.map{|t| [t.name.downcase,t.permalink.downcase]}.flatten.include?(taxon.strip.downcase)
      when Integer
        self.taxons.map{|t| t.id}.include?(taxon)
      when Taxon
        self.taxons.include?(taxon)
      else
        false
    end
  end

end

app/models/spree/product_taxon.rb
class Spree::ProductTaxon < ActiveRecord::Base
  belongs_to :product
  belongs_to :taxon
  default_scope :order=>'spree_product_taxons.position'
  acts_as_list :scope=>:taxon
  attr_accessible :product_id, :taxon_id
end

app/models/spree/taxon_decorator.rb
Spree::Taxon.class_eval do
  has_many :product_taxons,:order=>'spree_product_taxons.position'
  has_many :products, :through=>:product_taxons, :order=>'spree_product_taxons.position'
end

app/controllers/spree/admin/product_taxons_controller.rb
module Spree
	module Admin
		class ProductTaxonsController < ResourceController
		  def positions
		    @taxon = Spree::Taxon.find(params[:taxon_id])
        # List of taxons, beginnning with a virtual taxons for Home, and then all taxons with pts
       # @taxon = Spree::Taxon.find(params[:id])
        #@taxons << Spree::Taxon.new({:name => t('main_index')})
        #@taxons |= Spree::Taxon.joins(:product_taxons).order(:name)
      end
      
      def taxon_sort
        @taxons = Spree::Taxon.where("permalink" => ["k", "marka"])
      end
      
      def product_position
        @taxon = Spree::Taxon.find(params[:taxon_id])
      end
      
		end
	end
end

app/controllers/spree/admin/taxons_controller_decorator.rb
Spree::Admin::TaxonsController.class_eval do

  def reorder_products
    params[:product_taxons].each_with_index do |ptid, idx|
      pt = Spree::ProductTaxon.find(ptid.to_i)
      pt.insert_at(idx)
    end
    head :created
  end

end

app/views/spree/admin/product_taxons/_product_list.html.erb
<ul class="products_ul">
<%
  if @taxon.id
    products = @taxon.products.available
  else
    products = Spree::Product.available
  end
  
  #collect the pts for this taxon from each product 
  product_taxons = products.collect {|p| p.product_taxons.where(:taxon_id => taxon.id || 0).first }
%>
<% unless product_taxons.nil? %>
<% product_taxons.compact.each do |pt| %>
  <li id="product_taxons_<%=pt.id%>">
   <span class="handle">≡</span>
   <%= image_tag pt.product.images.first.attachment.url(:mini) unless pt.product.images.empty? %>
   <%= h pt.product.name %>
  </li>
<% end %>
</ul>
<% end %>

app/views/spree/admin/product_taxons/positions.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>
<h1><%= t('positions_for_products_in_taxons') %></h1>

  <h2><%= @taxon.name %></h2>
  
  <%= render :partial=> 'product_list', :locals => {:taxon => @taxon} %>
	<% content_for :head do %>
	  <script type="text/javascript">
			jQuery(document).ready(function(){
			  $('.products_ul').sortable(
			    { items:'li',
			      containment:'parent',
			      axis:'y',
			      handle:'.handle',
			      update: function(){
			        $.post('/admin/taxons/reorder_products/<%=@taxon.id || 0%>',
			               '_method=put&'+$(this).sortable('serialize'))
			      }
			    }
			  )
			});
	  </script>
	<% end %>

app/views/spree/admin/product_taxons/product_position.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>
<h1><%= t('positions_for_products_in_taxons') %></h1>

  <h2><%= @taxon.name %></h2>
  
  <%= render :partial=> 'product_list', :locals => {:taxon => taxon} %>
	<% content_for :head do %>
	  <script type="text/javascript">
			jQuery(document).ready(function(){
			  $('.products_ul').sortable(
			    { items:'li',
			      containment:'parent',
			      axis:'y',
			      handle:'.handle',
			      update: function(){
			        $.post('/admin/taxons/reorder_products/<%=taxon.id || 0%>',
			               '_method=put&'+$(this).sortable('serialize'))
			      }
			    }
			  )
			});
	  </script>
	<% end %>

app/views/spree/admin/product_taxons/taxon_sort.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>
<h1><%= t('positions_for_products_in_taxons') %></h1>

<ul class="taxons_ul">

<% @taxons.each do |t| %>
  <li id="taxons_<%=t.id%>">
   <span class="handle">≡</span>
   <%= h t.name %>
   
   <ul class="taxons_ul" >
   	<% t.children.each do |tc| %>
   	<li id="taxons_<%= tc.id %>">
   		<span class="handle">></span>
   		<% if tc.children.empty? %>
   			<%#= link_to tc.name, admin_product_position_url(tc) %>
			<%= link_to tc.name, (admin_product_sort_url  + '?taxon_id=' + tc.id.to_s) %>
   		<% else %>
   			<%= h tc.name %>
   		<% end %>
   		
   		   <ul class="taxons_ul" >
		   	<% tc.children.each do |tcc| %>
		   	<li id="taxons_<%= tcc.id %>">
	   			<span class="handle">></span>
   				<% if tcc.children.empty? %>
   					<%= link_to tcc.name, (admin_product_sort_url + '?taxon_id=' + tcc.id.to_s) %>
   				<% else %>
   					<%= h tcc.name %>
   				<% end %>
   			</li>
   			<% end %>
   		   </ul>

   		
   	</li>
   	<% end %>
   </ul>
   
  </li>
<% end %>
</ul>